### ISSUE TITLE
Harmony Plugin deaktiviert sich

### ISSUE THREAD

**Issue by SBF2978** [thkl/Homematic-Virtual-Interface#105]
Hallo,
Ich habe einen Pi4B neu aufgesetzt mit der aktuellsten raspberrymatic. HVL mit dem 0.0.10 Addon installiert, zweimal neugestartet und dann sowohl das Hue plugin, als auch das harmony plugin installiert und aktiviert. Beides ließ sich einrichten (Hue Geräte werden zwar nicht durchgereicht, aber das ist ja bereits bekannt), jedoch deaktiviert sich nach einem weiteren reboot das harmony plugin und lässt sich auch nicht wieder aktivieren.
Die Problematik trat das erste mal nach dem Update der HVL auf, vorher lief es ohne Probleme.
Gibt es bei der Installation etwas zu beachten?
Hatte schon jemand mit dem selben Problem zu kämpfen oder welche Informationen kann ich noch liefern um das Problem einzukreisen? Logfile?
Vielen Dank

**Comment by thkl** [comment]
Bitte mal ins Log schauen 👀 und das ggf hier posten wenn Errors dort aufschlagen.

**Comment by SBF2978** [comment]
Ich hoffe das funktioniert als PDF...
[logfile.pdf](https://github.com/thkl/Homematic-Virtual-Interface/files/4213861/logfile.pdf)

**Comment by thkl** [comment]
Ok, ich habe das Update des Hue Und Harmony Moduls auf das neue node-Hue-api fertig. 
Ich würde das in Kürze mal als Update veröffentlichen. Problem ist, das das aktuelle Hue/Harmony Plugin sich die latest Version vom Node-hue-api zieht und das ist nicht mehr kompatibel zum Plugin.

**Comment by thkl** [comment]
Ich habe das Hue Plugin für die Version 0.0.51 mal als Beta gepackt.
Installation: ssh auf die Raspberrymatic ..

```
cd /usr/local/addons/hvl/
npm install homematic-virtual-huedevice@0.0.51
```

Damit wird Version 0.0.51 drüber gebügelt.
HVL neu starten und dann sollten die Lampen angezeigt werden und auch in der CCU landen.
Ich hab das jetzt zumindest 3x auf einer VirtualBox RM ausprobiert.

**Comment by thkl** [comment]
Das gleich für Harmony

```
cd /usr/local/addons/hvl/
npm install homematic-virtual-harmonydevice@0.0.41
```

**Comment by SBF2978** [comment]
Hallo Thomas,
vielen Dank für den schnellen Lösungsansatz, ich habe beides ausgeführt, und neu gestartet. Das Harmony Plugin lässt sich jedoch weiterhin nicht aktivieren und im Hue Plugin werden jetzt keine Lampen mehr angezeigt. Ich habe das aktuelle Logfile angehangen und auch drei Screenshots

[Logfile.pdf](https://github.com/thkl/Homematic-Virtual-Interface/files/4215214/Logfile.pdf)

![Hue Plugin](https://user-images.githubusercontent.com/61122220/74674647-23826c80-51b2-11ea-88dc-82d6e7e30cc6.JPG)
![Plugins1](https://user-images.githubusercontent.com/61122220/74674654-267d5d00-51b2-11ea-99c0-1b4c71db56c4.JPG)
![plugins2](https://user-images.githubusercontent.com/61122220/74674663-28dfb700-51b2-11ea-95ba-c2dc9c674232.JPG)

**Comment by SBF2978** [comment]
Nochmal ich...
Nachdem ich HVL noch einmal komplett deinstalliert habe, per ssh alle Ordner mit HVL gelöscht, danach HVL neu installiert, zwei Mal gestartet, deine Schritte oben durchgeführt, ein weiteres Mal gestartet habe, waren beide Plugins aktiv und ich konnte die Settings eintragen. Lampen wurden trotzdem nicht durchgereicht und nach einem weiteren Neustart bin ich wieder auf Anfang. Harmony Plugin ist deaktiviert und lässt sich nicht reaktivieren.

[Logfile.pdf](https://github.com/thkl/Homematic-Virtual-Interface/files/4215355/Logfile.pdf)

**Comment by thkl** [comment]
Das Harmony Plugin braucht eine neuere Core Version .. ich schau gerade das ich die gleich noch in der Beta veröffentlichen kann. Hue stirbt an einem Unbekannten Sensor .. da bin ich auch auf der Suche.

**Comment by SBF2978** [comment]
Ok, ich hatte eine Lampe aktuell angelernt, aber nicht angeschlossen. Daran kann es nicht liegen, oder?

**Comment by thkl** [comment]
so 
```
cd /usr/local/addons/hvl/
npm install homematic-virtual-interface@0.2.77
```

Wenn die Lampen auf der Website von HVL angezeigt werden, aber nicht in der CCU sind dann bitte einmal den Button "Homematic Geräte erzeugen" auf der Hue Seite anklicken

**Comment by SBF2978** [comment]
Hallo Thomas,
nach diesem Update sind wieder beide Plugins aktiv, es werden jedoch noch keine Lampen angezeigt.
[Logfile.pdf](https://github.com/thkl/Homematic-Virtual-Interface/files/4215536/Logfile.pdf)
![1](https://user-images.githubusercontent.com/61122220/74678527-8debda80-51bb-11ea-9ec3-92717f9c1234.JPG)
![2](https://user-images.githubusercontent.com/61122220/74678530-90e6cb00-51bb-11ea-906a-cd58f876986f.JPG)

**Comment by thkl** [comment]
Dein Log sagt immer noch das das Plugin über einen geofence Sensor stolpert, den er nicht kennt. Ich schalte mal die Sensor Suche aus .. dauert einen Moment und dann gibts ne neue Beta ;)

**Comment by SBF2978** [comment]
Ich hatte nie einen geofence sensor aktiv...

**Comment by thkl** [comment]
tja das Log behauptet gegenteiliges .. egal 

```
cd /usr/local/addons/hvl/
npm install homematic-virtual-huedevice@0.0.52
```

**Comment by SBF2978** [comment]
hmmm, 
ich hab's  installiert, neugestartet und immer noch keine Lampen...

Mon Feb 17 2020 20:14:42 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [ERROR] - Sorry there was an error while initializing the lights ReferenceError: serial is not defined
Mon Feb 17 2020 20:14:42 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [INFO] - initialization completed
Mon Feb 17 2020 20:14:32 GMT+0100 (CET)[HomematicLogicalLayer] [WARN] - corpsed devices : [{"address":"HUE000010","regaid":"13065"},{"address":"HUES_000","regaid":"11929"},{"address":"HUE00005","regaid":"13050"},{"address":"HUE00008","regaid":"13055"},{"address":"HUE00009","regaid":"13060"},{"address":"OSRPLG03","regaid":"8206"},{"address":"HUE00007","regaid":"11873"}]
Mon Feb 17 2020 20:14:32 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - looking for corpses
Mon Feb 17 2020 20:13:41 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [ERROR] - Sorry there was an error while initializing the lights ReferenceError: serial is not defined
Mon Feb 17 2020 20:13:41 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [INFO] - initialization completed
Mon Feb 17 2020 20:13:35 GMT+0100 (CET)[homematic-virtual-harmonydevice - Harmony] [INFO] - fetching activities
Mon Feb 17 2020 20:13:35 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - 2 dude(s) to publish events
Mon Feb 17 2020 20:13:35 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - connection request at http://192.168.178.20:9292/bidcos with callback HVL_java .. live is good
Mon Feb 17 2020 20:13:35 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init new consumer with host "192.168.178.20" at port 9292 path /bidcos
Mon Feb 17 2020 20:13:35 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - Init RPC with saved callback at http://192.168.178.20:9292/bidcos
Mon Feb 17 2020 20:13:34 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [INFO] - initialization completed
Mon Feb 17 2020 20:13:33 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [ERROR] - Sorry there was an error while initializing the lights ReferenceError: serial is not defined
Mon Feb 17 2020 20:13:33 GMT+0100 (CET)[Logging System] [INFO] - 0 Logentries removed
Mon Feb 17 2020 20:13:32 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - apply interface Name HVL to all devices
Mon Feb 17 2020 20:13:32 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - CCU Response for ...Value ("") Error : ()
Mon Feb 17 2020 20:13:32 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - CCU is alive
Mon Feb 17 2020 20:13:32 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - CCU InterfaceList [{"name":"BidCos-RF"},{"name":"VirtualDevices"},{"name":"HmIP-RF"},{"name":"CUxD"},{"name":"HVL"},{"name":"hmvirtual"}]
Mon Feb 17 2020 20:13:32 GMT+0100 (CET)[ConfigurationServer] [INFO] - Configuration Server is listening on: Port 8300
Mon Feb 17 2020 20:13:32 GMT+0100 (CET)[homematic-virtual-harmonydevice - Harmony] [INFO] - HarmonyHueServer Server is listening on: Port 7001

**Comment by thkl** [comment]
das Problem liegt hier : 

Mon Feb 17 2020 20:14:42 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [ERROR] - Sorry there was an error while initializing the lights ReferenceError: serial is not defined

Ich würde mal eine Version bauen, die bissel mehr loggt ...

**Comment by thkl** [comment]
Sie 0.0.53 sollte jetzt mehr loggen (die Daten die von der bridge kommen) und nicht mehr komplett das Einlesen abbrechen wenn es zu einem Fehler kommt. Ich vermute mal, es liegt an dem Osram Stecker der da auftaucht. Das ist der Einzige, den ich nicht hier zum Testen habe ;)

**Comment by SBF2978** [comment]
Ich denke, wir haben die Lösung gefunden. Ich hatte neben den Original Hue Lampen noch ein Osram Plug und eine Zigbee Lampe über die Hue Bridge verbunden. Ich habe beide in der Hue app gelöscht und nun werden die original Hue Lampen im Hue plugin angezeigt.
In der alten Version haben jedoch auch diese einwandfrei funktioniert. Ich hatte bis zum Update nichts an der Konfig geändert

**Comment by SBF2978** [comment]
ich werde nacheinander beide noch einmal hinzufügen und dann jeweils den log laufen lassen.

**Comment by thkl** [comment]
siehe oben ;) .. einer von beiden liefert keine Seriennummer , die ich aber für die eindeutige Identifizierung benötige ..muss ich halt eine generieren .. aber mit dem Log aus der 0.0.53 komme ich da weiter ... (bitte als Text Datei anhängen , nicht als PDF ;) )

**Comment by SBF2978** [comment]
Also es scheint wirklich der Osram Plug zu sein. Ich habe unten mal einen Scrennshot angehangen wie er vor dem Update in RM eingebunden war:

Mon Feb 17 2020 21:03:45 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [ERROR] - Sorry there was an error while initializing the lights ReferenceError: serial is not defined
Mon Feb 17 2020 21:03:45 GMT+0100 (CET)[homematic-virtual-huedevice - Hue] [INFO] - initialization completed.

![Unbenannt](https://user-images.githubusercontent.com/61122220/74683530-89c6b980-51c9-11ea-8bd4-5f8bf80d4ac3.JPG)

**Comment by thkl** [comment]
Schon auf 0.0.53 aktualisiert .. da wird mehr log ausgeworfen .. inkl dem JSON was von der Hue Bridge für den Osram Plug kommt

**Comment by SBF2978** [comment]
ist drauf und es liegt wohl an beiden, Osram und Zigbee Lampen. Beide sind wieder der Hue Bridge hinzugefügt, beide werden im Plugin nicht übernommen
[1.txt](https://github.com/thkl/Homematic-Virtual-Interface/files/4216035/1.txt)

**Comment by thkl** [comment]
Könnte mit der 0.0.54 jetzt aber funktionieren ...
Btw: Damit die Harmony die Hue Lampen übernimmt muss dort in den Einstellungen der Name des  Hue Plugins (also Hue) eingetragen werden.

**Comment by SBF2978** [comment]
Schau mal einer an... Nach einem Neustart sind jetzt beide drin, auch wenn die SN des Osram Plugs etwas kryptisch ist... ist mir aber egal:

![image](https://user-images.githubusercontent.com/61122220/74684057-19b93300-51cb-11ea-983d-7e1d4b12aaf6.png)

PS: werde trotzdem noch die 0.0.54 installieren

**Comment by SBF2978** [comment]
ich hatte das "Hue" im harmony Plugin vorhin testweise rausgenommen und noch nicht wieder eingefügt

**Comment by SBF2978** [comment]
Genial!!!
Alles wieder so früher....

![image](https://user-images.githubusercontent.com/61122220/74684451-3f930780-51cc-11ea-8635-4a249ec63419.png)

![image](https://user-images.githubusercontent.com/61122220/74684568-913b9200-51cc-11ea-88d6-681f952c3fb1.png)

Vielen, Vielen Dank für dein Engagement und vor allem deine Geduld!!
Wenn ich noch irgendetwas testen kann, sag einfach Bescheid.

**Comment by thkl** [comment]
;) .. abgesehen davon, das intern alles ganz anders ist .. 
Wenn es passt bitte mal 1-2 Tage laufen lassen und wenn nichts kaputt geht kann ich das Ganze ja publishen

**Comment by SBF2978** [comment]
Ich werde auf jeden Fall berichten ob in den kommenden Tagen irgendetwas passiert oder hoffentlich nicht passiert.

**Comment by SBF2978** [comment]
So leid es mir tut, die ersten Dinge sind schon aufgefallen:
1. nach einem Neustart werden die Hue Lampen nicht im Harmony Plugin angezeigt, erst bei einem erneuten Speichern der Einstellungen im Plugin
2. die in der CCU generierten Hue Geräte sind nicht steuerbar
3. wenn die Geräte in der CCU abgelernt werden, kann man sie nicht wieder generieren und in den Posteingang legen. Auch aus dem Service Mode können sie auch nicht erneut angelegt werden. 

[1.txt](https://github.com/thkl/Homematic-Virtual-Interface/files/4216170/1.txt)

**Comment by thkl** [comment]
Zu 2. gibt’s beim Versuch irgendwelche Fehlermeldungen im Log ?

**Comment by SBF2978** [comment]
Hallo Thomas,
Tschuldige bin erst jetzt nach Hause gekommen um es zu testen. Also alle Hue Devices in der CCu lassen sich nicht steuern. Komischerweise legt sich dazu nichts im Logfile ab, sondern immer nur ein  Error bezüglich des Osram Plugs. Ich habe mal einen kurzen AUszug kopiert:

Tue Feb 18 2020 21:24:44 GMT+0100 (CET)[Homematic Virtual Interface.Server] [ERROR] - Unhandled Rejection at: Promise {} reason: ReferenceError: di_channel is not defined
    at /usr/local/addons/hvl/node_modules/homematic-virtual-huedevice/HueDeviceOsramPlug.js:101:5
Tue Feb 18 2020 21:24:44 GMT+0100 (CET)[Homematic Virtual Interface.Server] [ERROR] - Unhandled Rejection at: Promise {} reason: ReferenceError: di_channel is not defined
    at /usr/local/addons/hvl/node_modules/homematic-virtual-huedevice/HueDeviceOsramPlug.js:101:5
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
Tue Feb 18 2020 21:24:43 GMT+0100 (CET)[Homematic Virtual Interface.Server] [ERROR] - Unhandled Rejection at: Promise {} reason: ReferenceError: di_channel is not defined
    at /usr/local/addons/hvl/node_modules/homematic-virtual-huedevice/HueDeviceOsramPlug.js:101:5
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
Tue Feb 18 2020 21:24:43 GMT+0100 (CET)[Homematic Virtual Interface.Server] [ERROR] - Unhandled Rejection at: Promise {} reason: ReferenceError: di_channel is not defined
    at /usr/local/addons/hvl/node_modules/homematic-virtual-huedevice/HueDeviceOsramPlug.js:101:5
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)

**Comment by SBF2978** [comment]
Ich werde den Plug jetzt mal von der Original Hue Bridge löschen und dann erneut probieren

**Comment by thkl** [comment]
Ok den Error fix ich mal noch ...

**Comment by SBF2978** [comment]
Ich schaue mal, ob im Logfile der CCU irgendetwas zu erkennen ist. Das müsste dann u.U. zu Jens Maus

**Comment by thkl** [comment]
Ne auf meinem Testsystem gehts ja auch. Das läuf t auf einer aktuellen Version.   Das findet sich schon.

**Comment by SBF2978** [comment]
[logfile.txt](https://github.com/thkl/Homematic-Virtual-Interface/files/4221573/logfile.txt)

**Comment by SBF2978** [comment]
nachdem ich den Osram Plug von der Hue Bridge gelöscht habe, die CCU neugestartet, lassen sich die Hue devices steuern. Der Fehler liegt also tatsächlich dort

**Comment by thkl** [comment]
👍 dann fix ich den morgen noch.

**Comment by SBF2978** [comment]
Super, vielen Dank. Und wenn du die Möglichkeit hast den 1. Fehler herauszufinden warum die Hue Lampen im Harmony Plugin erst nach einem weiteren Speichern in den Einstellungen des Plugins wieder sichtbar sind.

**Comment by thkl** [comment]
so das Hue Plugin gibt es jetzt in 0.0.55 da sollte der Fehler mit dem Osram Stecker behoben sein.

**Comment by thkl** [comment]
zur Bonusfrage, ja ich kann es mir vorstellen. Und zwar könnte es sein, das das Harmony Plugin geladen ist, bevor das Hue Plugin fertig ist ... für das Logic Plugin gibt es da eine dependencies Funktion, die auf andere Plugins wartet .. ich schau mal das ich das gleiche dem Harmony Plugin verpasse. Denn das fragt neuerdings direkt beim Hue Plugin nach den Lampen und steuert diese auch durch Messages an das Hue Plugin. Spart eine Client Verbindung zur Hue Bridge ...

**Comment by thkl** [comment]
so .. zuerst HVL auf 0.2.78 updaten und dann das Harmony Plugin auf 0.0.42 ... dann in den Einstellungen des Harmony Plugins unten bei Dependencies Hue eintragen und dann sollte das funktionieren dann wartet das Harmony Plugin bis Hue fertig initialisiert ist ..

**Comment by SBF2978** [comment]
N'abend Thomas,
das Bonusproblem zu 100% gelöst! Mit dem Plug kämpfe ich gerade noch.
- Plug in der Original Hue Bridge hinzugefügt
- im Hue Plugin zu sehen
- lässt sich nicht steuern über die CCU (kein Eintrag im Logfile)
- die Harmony  verliert die Verbindung zur virtuellen Hue Bridge, auch ein neues Pairing scheitert
dazu findet sich im Logfile 
Wed Feb 19 2020 20:06:47 GMT+0100 (CET)[homematic-virtual-harmonydevice - Harmony] [ERROR] - Harmony Hue Error 101  Message link button not pressed

**Comment by SBF2978** [comment]
Ich habe allerdings zwei weitere "Probleme" gefunden:
1. all Hue Lampen, die ich über die Harmony steuere, flackern sowohl beim einschalten, als auch beim ausschalten.
2. Ich habe einen HM Dimmer (HM-LC-Dim1TPBU-FM). Dieser lässt sich über die Harmony zwar einschalten und dimmen, jedoch nicht mehr ausschalten. 
Beide Punkte sind vor den Updates nicht aufgetreten.

**Comment by SBF2978** [comment]
So, habe den Plug mal wieder aus der Hue Bridge gelöscht und siehe da, die Harmony findet die virtuelle Bridge wieder

**Comment by thkl** [comment]
verdammt, dieser blöde Osram Plug, ist das einzige Gerät, was ich nicht habe ... ich schau mal ob ich das irgendwie simulieren kann

**Comment by SBF2978** [comment]
Hallo Thomas,
nachdem ich gestern meine Raspberrymatic neu aufgesetzt habe und alles installiert habe, möchte ich heute kurz Bericht erstatten.
Zu allererst aber möchte ich mich jedoch bei dir bedanken!

Was mir bisher aufgefallen ist:

1. in der Harmony eingebundene Hue Lampen (z.B. Play, Lightstrip) lassen sich schalten und dimmen, jedoch nicht in der Farbe ändern.
2. beim einschalten aller Hue Lampen über die Harmony flackern diese beim ein- und ausschalten (fast so als würde man sie neu anlernen). Der Hue Lightstrip spielt beim einschalten sogar ein wenig Disco
3. Der Homematic Dimmer  (HM-LC-Dim1TPBU-FM) lässt sich einschalten und dimmen, aber nicht wieder ausschalten.

Gruß
Frank
