### ISSUE TITLE
DarkSkyWeather 0.0.3 Plugin läßt sich nicht aktivieren

### ISSUE THREAD

**Issue by steckenpferd** [thkl/Homematic-Virtual-Interface#116]
Hi,

habe für meinen RaspberryMatic hier von github die Datei **hvl-raspb-0.0.10.tar.gz** heruntergeladen und installiert. Was mich als erstes wundert ist das **Version 0.9 statt 0.10** dasteht.
![grafik](https://user-images.githubusercontent.com/39061622/79771527-34c13400-832f-11ea-8f78-d97cf12b76bd.png)

Dann habe ich das Plugin OpenweatherMap 0.0.7 installiert - aktiviert, Posteingang Gerät eingerichtet und mit API Key und ID versorgt - klappt anonsten aber wunderbar (aber kein Sonnenscheindauer und auch nicht Helligkeit -bekommt man die Werte überhaupt über das Plugin?)  und der virtuelle KS550 aktualisiert seine Werte.

Danach dachte ich vergleiche ich es mal mit dem **DarkSkyWeather 0.0.3 Plugin**. Plugin installiert, danach versucht das Plugin zu aktivieren aber es läßt sich leider nicht aktivieren. Im Posteingang erscheint aber der HM-WDS100 s. Bild. 
![grafik](https://user-images.githubusercontent.com/39061622/79771281-ddbb5f00-832e-11ea-837b-a962c717712b.png)

Auch mehrere Reboots der HVL und auch des RaspberryMatic brachten keine Änderung. DarkSkyWeather Plugin läßt sich nicht aktivieren s. LOG Daten:

Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [ERROR] - Cannot initialize DarkSky - TypeError: Cannot read property 'debug' of undefined
    at DarkSkyPlatform.fetchWeather (/usr/local/addons/hvl/node_modules/homematic-virtual-darkskyweather/DarkSkyPlatform.js:104:13)
    at DarkSkyPlatform.init (/usr/local/addons/hvl/node_modules/homematic-virtual-darkskyweather/DarkSkyPlatform.js:45:7)
    at new module.exports (/usr/local/addons/hvl/node_modules/homematic-virtual-darkskyweather/index.js:9:17)
    at Server._loadPlugins (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1287:40)
    at Server.reloadPlugins (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:248:25)
    at Server.activatePlugin (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1106:10)
    at Server.handleConfigurationRequest (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:669:30)
    at ConfigurationServer.<anonymous> (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:132:26)
    at ConfigurationServer.emit (events.js:210:5)
    at Server.handleRequest (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/ConfigurationServer.js:106:26)
Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[homematic-virtual-darkskyweather - DarkSky] [INFO] - initialization completed true
Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [INFO] - Trying to load Localization from /usr/local/addons/hvl/node_modules/homematic-virtual-darkskyweather/Localizable.strings
Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[HomematicLogicalLayer] [INFO] - Skip HMServer
Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[HomematicDevice] [INFO] - Owner is DarkSky
Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [INFO] - Loaded plugin: homematic-virtual-openweathermapdevice
Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [INFO] - Loaded plugin: homematic-virtual-darkskyweather
Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [INFO] - Reload .. shutdown all plugins
Mon Apr 20 2020 18:12:14 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [INFO] - Found homematic-virtual-darkskyweather set disable to false

PS. Was mir noch aufgefallen war das ein Reboot des HVL auch nach 10min nicht das Addon nicht zurück kam und ich dann den ganzen RaspberryMatic neu starten musste.

PS II: Plugin - Weatherunderground ließ sich Problemlos aktivieren - aber dafür erhält mein kein API mehr von dennen

**Comment by steckenpferd** [comment]
Sehe gerade das es von DarkSky sowieso keine API mehr geben wird
https://www.computerwoche.de/a/amp/apple-kauft-wetterdienst-und-veraergert-android-nutzer,3548753

**Comment by comtel2000** [comment]
Ich werde noch eine 0.0.4 vom DarkSky mit dem Fix releasen. Aber da DarkSky schon keine neuen API keys vergibt, wird das sicher hier enden.

**Comment by comtel2000** [comment]
@thkl - ticket kann geschlossen werden
