### ISSUE TITLE
nanoleave-aurora plugin can not be activated

### ISSUE THREAD

**Issue by mflury** [thkl/Homematic-Virtual-Interface#53]
during activate of the nanoleave-aurora plugin the following error apears:

 Fri Nov 02 2018 00:14:39 GMT+0100 (CET)[Homematic Virtual Interface.Server] [ERROR] - Cannot initialize Aurora - TypeError: Cannot read property 'listEffects' of undefined
    at NanoleafAuroraPlatform.initApi (/usr/local/addons/hvl/node_modules/homematic-virtual-nanoleafauroradevice/NanoleafAuroraPlatform.js:193:14)
    at NanoleafAuroraPlatform.init (/usr/local/addons/hvl/node_modules/homematic-virtual-nanoleafauroradevice/NanoleafAuroraPlatform.js:45:7)
    at new module.exports (/usr/local/addons/hvl/node_modules/homematic-virtual-nanoleafauroradevice/index.js:9:17)
    at Server._loadPlugins (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1201:26)
    at Server.reloadPlugins (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:227:22)
    at Server.activatePlugin (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1001:7)
    at Server.handleConfigurationRequest (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:608:14)
    at ConfigurationServer.<anonymous> (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:115:11)
    at emitOne (events.js:96:13)
    at ConfigurationServer.emit (events.js:188:7)

Platform ccu3 3.41.7 (same error as in previous release)

Cheers Matthias

**Comment by JensBonse** [comment]
Damit das funktioniert, musste du in der Datei aurora.js Zeile 218 korrigieren auf:
const requestOptions = this.makeGetRequestOptions('/effects/effectsList');

die Datei findet sich in dem Unterverzeichnis von /node_modules/homematic-virtual-nanoleafauroradevice/lib

Danach dann HMVI neustarten.

**Comment by JensBonse** [comment]
@thkl Das npm scheint noch die alte Version zu sein.
