### ISSUE TITLE
Sonos Geräte Suche funktioniert nicht

### ISSUE THREAD

**Issue by ajscat** [thkl/Homematic-Virtual-Interface#90]
Hallo,

wenn ich per Suche starten nach neuen Sonos Geräten suche bekomme ich folgende Fehlermeldung im log:

Caught exception: TypeError: Cannot read property 'forEach' of null
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/SonosPlatform.js:333:22
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/node-sonos/lib/sonos.js:1060:7
    at Parser.<anonymous> (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:1436:13)
Caught exception: TypeError: Cannot read property 'forEach' of null
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/SonosPlatform.js:333:22
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/node-sonos/lib/sonos.js:1060:7
    at Parser.<anonymous> (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:1436:13)
Caught exception: TypeError: Cannot read property 'forEach' of null
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/SonosPlatform.js:333:22
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/node-sonos/lib/sonos.js:1060:7
    at Parser.<anonymous> (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:1436:13)
Caught exception: TypeError: Cannot read property 'forEach' of null
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/SonosPlatform.js:333:22
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/node-sonos/lib/sonos.js:1060:7
    at Parser.<anonymous> (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:1436:13)
Caught exception: TypeError: Cannot read property 'forEach' of null
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/SonosPlatform.js:333:22
    at /home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/node-sonos/lib/sonos.js:1060:7
    at Parser.<anonymous> (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/hmvi/node_modules/homematic-virtual-sonosdevice/node_modules/sax/lib/sax.js:1436:13)

**Comment by thkl** [comment]
der Fehler ist schon hier in der GitHub Version korrigiert.
Ich hab eine neue Plugin Version 0.0.28 gebaut

**Comment by ajscat** [comment]
Danke! Der Fehler ist zwar weg aber Geräte werden keine gefunden

**Comment by thkl** [comment]
Ich werfe mal einen Blick

**Comment by thkl** [comment]
müsste mit Plugin Version 0.0.29 wieder gehen. Es gab da einige Änderungen im Sonos "API"

**Comment by ajscat** [comment]
Danke für deine Arbeit, denke aber nicht das es schon funktioniert. Kann ich dir noch irgendwelche Infos liefern?

**Comment by thkl** [comment]
Ich habe das jetzt mal auf einer leeren Rapsberrymatic mit einem leeren HVL getestet.
Die Sonos Player werden alle gefunden.

Man könnte die Player auch manuell zur config hinzufügen:

* es werden 3 Angaben benötigt : Name, IP und Seriennummer
all das bekomme man aus dem About Dialog der Sonos App.
Hier sind alle Player aufgelistet. Wichtig bei Stereopärchen ist der Linke entscheidend.

Die Seriennummer in HVL sind die ersten letzen 8 Stellen der Mac des Players vor dem : und ein 01 dran
Beispiel: Sonos About : 

Seriennummer: AB-CD-EF-98-76-54:3
```
{
          "name": "Player1",
          "serial": "SO_EF98765401",
          "host": "192.168.178.123"
  }
```
in der config.json gibt es einen Sonos Eintrag.
Ohne Player schaut der so aus:

```
{
 "type": "homematic-virtual-sonosdevice",
      "name": "Sonos",
      "disabled": false
}
```

mit 2 Playern:

```
    {
      "type": "homematic-virtual-sonosdevice",
      "name": "Sonos",
      "disabled": false,
      "player": [
        {
         "name": "Player1",
          "serial": "SO_EF98765401",
          "host": "192.168.178.123"
        },
        {
           "name": "Player2",
          "serial": "SO_9876543201",
          "host": "192.168.178.124"
        }
      ]
}
```

Bitte den richtigen json Syntax beachten sonst startet HVL nicht richtig.

**Comment by ajscat** [comment]
Suche klappt wieder! Vielen Dank! Jetzt wird mir nur noch nicht das Device auf der CCU erzeugt. Der Install Mode läuft und läuft....;-)

**Comment by thkl** [comment]
Die Player müssen noch im Plugin über den Player hinzufügen Button aktiviert werden. Erst dann wird ein HM Gerät erzeugt. Die Funktion schiebt den Player aber dann sofort in die CCU

**Comment by ajscat** [comment]
Sorry. Hab ich gemacht klappt aber leider nicht. Im debug Modus sehe ich auch keine Meldungen dazu.
Nur:
 repl  > ["system.listMethods","listDevices","getDeviceDescription","getLinks","getValue","setValue","getParamsetDescription","getParamsetId","getParamset","reportValueUsage","deleteDevice","getLinkPeers","system.methodHelp","putParamset","init","ping"]
[2020-01-21 15:36:07.209] [HomematicChannel][DEBUG] Channel 19 update Event COORDINATOR with true
[2020-01-21 15:36:07.210] [HomematicChannel][DEBUG] Ignore Value Change SO_3E08E04601:19.COORDINATOR event because the value doesnt change true vs true
[2020-01-21 15:36:07.211] [HomematicChannel][DEBUG] Channel 19 update Event ZONEGROUPID with SO_3E08E04601
[2020-01-21 15:36:07.212] [HomematicChannel][DEBUG] Ignore Value Change SO_3E08E04601:19.ZONEGROUPID event because the value doesnt change SO_3E08E04601 vs SO_3E08E04601
[2020-01-21 15:36:07.217] [HomematicChannel][DEBUG] Channel 19 update Event COORDINATOR with true
[2020-01-21 15:36:07.218] [HomematicChannel][DEBUG] Ignore Value Change SO_3E0B594801:19.COORDINATOR event because the value doesnt change true vs true
[2020-01-21 15:36:07.219] [HomematicChannel][DEBUG] Channel 19 update Event ZONEGROUPID with SO_3E0B594801
[2020-01-21 15:36:07.220] [HomematicChannel][DEBUG] Ignore Value Change SO_3E0B594801:19.ZONEGROUPID event because the value doesnt change SO_3E0B594801 vs SO_3E0B594801
[2020-01-21 15:36:07.252] [HomematicChannel][DEBUG] Channel 19 update Event COORDINATOR with true
[2020-01-21 15:36:07.253] [HomematicChannel][DEBUG] Ignore Value Change SO_B8344DB701:19.COORDINATOR event because the value doesnt change true vs true
[2020-01-21 15:36:07.254] [HomematicChannel][DEBUG] Channel 19 update Event ZONEGROUPID with SO_B8344DB701
[2020-01-21 15:36:07.255] [HomematicChannel][DEBUG] Ignore Value Change SO_B8344DB701:19.ZONEGROUPID event because the value doesnt change SO_B8344DB701 vs SO_B8344DB701

**Comment by thkl** [comment]
naja die Lautsprecher reden schon mal mit HVL .. 
Stehen die ggf unter ServiceMode/Gelöschte Geräte ?

**Comment by ajscat** [comment]
Nein da ist nichts. Wenn ich auf Install Mode klicke passiert auch nichts (Seite lädt, Balken erscheint und das wars. Mit dieser Funktion konnte man doch auch die Geräte wieder anlegen lassen oder?

**Comment by thkl** [comment]
ja, aber da wird im Prinzip nur einmal die CCU mit der Liste der Geräte vollgeschwallt.
ggf mal HVL im Debug mit -D starten dann sieht man  was zur CCU geschickt wird:

Nach dem Klick auf "Install Mode" gibt es sowas:

`
RPC Out -> method:newDevices | params 
`

+ folgend einem JSON mit allen Kanälen die an die CCU geschickt werden.
Da sollten sich dann die SO__ finden.

**Comment by ajscat** [comment]
Nur das kommt wenn ich die Funktion anwende:

 request index not handled by a plugin try mine
[2020-01-21 19:31:57.643] [Homematic Virtual Interface.Server][DEBUG] index is mine
[2020-01-21 19:31:57.648] [HomematicLogicalLayer][DEBUG] Will send to all Consumers
[2020-01-21 19:31:57.649] [HomematicLogicalLayer][INFO] Skip HMServer
[2020-01-21 19:32:07.317] [HomematicLogicalLayer][DEBUG] rpc < system.listMethods ()
[2020-01-21 19:32:07.319] [HomematicLogicalLayer][DEBUG] repl  > ["system.listMethods","listDevices","getDeviceDescription","getLinks","getValue","setValue","getParamsetDescription","getParamsetId","getParamset","reportValueUsage","deleteDevice","getLinkPeers","system.methodHelp","putParamset","init","ping"]
[2020-01-21 19:32:08.853] [HomematicChannel][DEBUG] Channel 19 update Event COORDINATOR with true
[2020-01-21 19:32:08.854] [HomematicChannel][DEBUG] Ignore Value Change SO_3E08E04601:19.COORDINATOR event because the value doesnt change true vs true
[2020-01-21 19:32:08.856] [HomematicChannel][DEBUG] Channel 19 update Event ZONEGROUPID with SO_3E08E04601
[2020-01-21 19:32:08.857] [HomematicChannel][DEBUG] Ignore Value Change

**Comment by thkl** [comment]
🧐🤔

**Comment by ajscat** [comment]
Vielleicht sollte ich noch erwähnen das ich bereits ein Gerät auf der CCU nutzte (hinzugefügt vor etwa 9 Monaten) und das der Ausgangspunkt war. Ich wollte nun meine anderen Geräte hinzufügen und da viel mir das mit der Suche auf...

**Comment by ajscat** [comment]
Hast du noch eine Idee? Der Install Mode funktioniert bei mir auch nicht. Die Seite geht nach einiger Zeit auf einen Timeout

**Comment by ajscat** [comment]
Es funktioniert nicht. Ich habe alle Geräte aus der CCU gelöscht. Es werden keine neuen Geräte im Posteingang mehr angezeigt. Kannst du dir das nochmal ansehen? Danke
